/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three';
import { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    letreroAleBt: THREE.Mesh
    letreroAle: THREE.Mesh
    vitrina2vidrio: THREE.Mesh
    vitrinaRedondaVidrio: THREE.Mesh
    hornoVidrio: THREE.Mesh
    tvPantalla: THREE.Mesh
    vaso: THREE.Mesh
    clases_Baked: THREE.Mesh
    redes_Baked: THREE.Mesh
    snacks_Baked: THREE.Mesh
    personalizados_Baked: THREE.Mesh
    postres_Baked: THREE.Mesh
    scene_Baked: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/ale3d03_expandido_c.glb') as unknown as GLTFResult
  const texture = useTexture('/MergedBake_Bake1_CyclesBake_COMBINED.001.jpg')
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;

  // Create a proper MeshBasicMaterial for baked geometry
  const bakedMaterial = React.useMemo(() => new THREE.MeshBasicMaterial({
    map: texture,
    toneMapped: false,
    side: THREE.DoubleSide
  }), [texture]);

  const materialEmission = React.useMemo(() => ({
    purple: new THREE.MeshBasicMaterial({ color: new THREE.Color('purple').multiplyScalar(30), toneMapped: false }),
    red: new THREE.MeshBasicMaterial({ color: new THREE.Color('red').multiplyScalar(30), toneMapped: false }),
    blue: new THREE.MeshBasicMaterial({ color: new THREE.Color('blue').multiplyScalar(30), toneMapped: false }),
    green: new THREE.MeshBasicMaterial({ color: new THREE.Color('green').multiplyScalar(30), toneMapped: false }),
    yellow: new THREE.MeshBasicMaterial({ color: new THREE.Color('yellow').multiplyScalar(30), toneMapped: false }),
    white: new THREE.MeshBasicMaterial({ color: new THREE.Color('white').multiplyScalar(30), toneMapped: false }),
  }), []);

  const materialGlass = React.useMemo(() => new THREE.MeshPhysicalMaterial({
    transparent: true,
    opacity: 0.4,
    roughness: 0.5,
    metalness: 0.5,
    side: THREE.DoubleSide,
  }), []);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.letreroAleBt.geometry} material={materialEmission.purple} position={[-3.214, 6.257, -6.87]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.letreroAle.geometry} material={materialEmission.purple} position={[-5.874, 7.142, -2.598]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.vitrina2vidrio.geometry} material={materialGlass} position={[4.645, 1.655, -2.531]} />
      <mesh geometry={nodes.vitrinaRedondaVidrio.geometry} material={materialGlass} position={[-2.023, 0.991, 1.993]} />
      <mesh geometry={nodes.hornoVidrio.geometry} material={materialGlass} position={[-4.158, 4.438, -4.462]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.tvPantalla.geometry} material={bakedMaterial} position={[3.699, 6.297, -6.881]} />
      <mesh geometry={nodes.vaso.geometry} material={bakedMaterial} position={[1.055, 3.453, -5.718]} />
      <mesh geometry={nodes.clases_Baked.geometry} material={bakedMaterial} position={[1.499, 3.661, -5.89]} rotation={[0, -1.342, 0.173]} />
      <mesh geometry={nodes.redes_Baked.geometry} material={bakedMaterial} position={[-5.929, 5.223, -2.29]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.snacks_Baked.geometry} material={bakedMaterial} position={[4.056, 3.274, -3.429]} />
      <mesh geometry={nodes.personalizados_Baked.geometry} material={bakedMaterial} position={[4.688, 1.146, -5.944]} rotation={[0, 1.456, 0]} />
      <mesh geometry={nodes.postres_Baked.geometry} material={bakedMaterial} position={[0.284, 1.398, 4.174]} />
      <mesh geometry={nodes.scene_Baked.geometry} material={bakedMaterial} position={[3.996, 3.155, -1.583]} />
    </group>
  )
}

useGLTF.preload('/ale3d03_expandido_c.glb')
